###
POST http://localhost:6061/api/contacts HTTP/1.1
Content-Type: application/json

{
  "name": "Aldo Lozano",
  "phone": 8184715123,
  "date": "16/03"
}

###
GET http://localhost:6061/api/contacts HTTP/1.1

###
GET http://localhost:6061/api/contacts/62318772a01b055e29cd40d3 HTTP/1.1

###
PUT http://localhost:6061/api/contacts/62318e568186edcf9ad5b3a0 HTTP/1.1
Content-Type: application/json

{
  "name": "Salvador Rico",
  "phone": 8261037365,
  "date": "19/01"
}

###
DELETE http://localhost:6061/api/contacts/62318e568186edcf9ad5b3a0 HTTP/1.1